# Generated by Django 5.2.17 on 2026-09-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=60, verbose_name='сессия')),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='источник')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='кампания')),
                ('utm_content', models.CharField(blank=True, max_length=100, verbose_name='content')),
                ('utm_term', models.CharField(blank=True, max_length=100, verbose_name='term')),
                ('referrer', models.CharField(blank=True, max_length=500, verbose_name='источник перехода')),
                ('landing_path', models.CharField(blank=True, max_length=300, verbose_name='страница входа')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создан')),
            ],
            options={
                'verbose_name': 'визит',
                'verbose_name_plural': 'визиты',
                'ordering': ['-created'],
            },
        ),
    ]
