# Generated by Django 5.2.17 on 2026-09-29 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='код')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('is_required', models.BooleanField(default=False, verbose_name='обязательная')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'группа опций',
                'verbose_name_plural': 'группы опций',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('price_delta', models.IntegerField(default=0, verbose_name='доплата, ₽')),
                ('is_available', models.BooleanField(default=True, verbose_name='доступна')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='pricing.optiongroup', verbose_name='группа')),
            ],
            options={
                'verbose_name': 'опция',
                'verbose_name_plural': 'опции',
                'ordering': ['sort', 'id'],
            },
        ),
    ]
