# Generated by Django 5.2.17 on 2026-09-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='код')),
                ('percent', models.PositiveSmallIntegerField(default=10, verbose_name='скидка, %')),
                ('active', models.BooleanField(default=True, verbose_name='активен')),
            ],
            options={
                'verbose_name': 'промокод',
                'verbose_name_plural': 'промокоды',
                'ordering': ['code'],
            },
        ),
    ]
