# Generated by Django 5.2.17 on 2026-09-29 08:35

import apps.users.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='телефон')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='имя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='почта')),
                ('is_staff', models.BooleanField(default=False, verbose_name='сотрудник')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='регистрация')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_address', models.CharField(blank=True, max_length=300, verbose_name='адрес по умолчанию')),
                ('consent_pdp_at', models.DateTimeField(blank=True, null=True, verbose_name='согласие на ПД')),
                ('consent_pdp_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP согласия')),
                ('pd_version', models.CharField(blank=True, max_length=20, verbose_name='версия согласия')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
            },
        ),
    ]
