# Generated by Django 5.2.17 on 2026-09-29 08:35

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='что случилось')),
                ('resolved', models.BooleanField(default=False, verbose_name='решено')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
            ],
            options={
                'verbose_name': 'жалоба',
                'verbose_name_plural': 'жалобы',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=apps.orders.models.generate_number, max_length=20, unique=True, verbose_name='номер')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('paid', 'Оплачен'), ('delivered', 'Выполнен')], db_index=True, default='new', max_length=16, verbose_name='статус')),
                ('spec', models.JSONField(blank=True, default=dict, verbose_name='спецификация')),
                ('price_items', models.JSONField(blank=True, default=list, verbose_name='разбивка по позициям')),
                ('subtotal', models.IntegerField(default=0, verbose_name='сумма торта')),
                ('total', models.IntegerField(default=0, verbose_name='итого')),
                ('discount', models.IntegerField(default=0, verbose_name='скидка')),
                ('delivery_date', models.DateField(db_index=True, verbose_name='дата доставки')),
                ('delivery_time', models.TimeField(verbose_name='время доставки')),
                ('is_rush', models.BooleanField(default=False, verbose_name='срочный')),
                ('rush_amount', models.IntegerField(default=0, verbose_name='надбавка за срочность')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='адрес доставки')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий к заказу')),
                ('courier_comment', models.TextField(blank=True, verbose_name='комментарий для курьера')),
                ('pd_consent_at', models.DateTimeField(blank=True, null=True, verbose_name='согласие на ПД')),
                ('pd_consent_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP согласия')),
                ('pd_version', models.CharField(blank=True, max_length=20, verbose_name='версия согласия')),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='источник')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='кампания')),
                ('utm_content', models.CharField(blank=True, max_length=100, verbose_name='content')),
                ('utm_term', models.CharField(blank=True, max_length=100, verbose_name='term')),
                ('referrer', models.CharField(blank=True, max_length=500, verbose_name='источник перехода')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='сессия')),
                ('is_rescheduled', models.BooleanField(default=False, verbose_name='перенесён')),
                ('reschedule_note', models.CharField(blank=True, max_length=300, verbose_name='причина переноса')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создан')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ['delivery_date', 'delivery_time'],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('status', 'Статус изменён'), ('rescheduled', 'Новые сроки доставки'), ('issue', 'Жалоба'), ('paid', 'Оплата получена')], default='status', max_length=20, verbose_name='тип')),
                ('text', models.CharField(blank=True, max_length=300, verbose_name='текст')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
            ],
            options={
                'verbose_name': 'событие заказа',
                'verbose_name_plural': 'события заказа',
                'ordering': ['created'],
            },
        ),
    ]
