# Generated by Django 5.2.17 on 2026-09-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='адрес')),
                ('price', models.IntegerField(default=0, verbose_name='цена от, ₽')),
                ('image', models.CharField(blank=True, max_length=300, verbose_name='картинка')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('occasion', models.CharField(db_index=True, max_length=100, verbose_name='повод')),
                ('is_active', models.BooleanField(default=True, verbose_name='в каталоге')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'торт',
                'verbose_name_plural': 'торты',
                'ordering': ['occasion', 'sort', 'id'],
            },
        ),
    ]
