# Generated by Django 5.2.17 on 2026-09-29 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('yookassa', 'ЮKassa')], default='yookassa', max_length=20, verbose_name='провайдер')),
                ('provider_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID у провайдера')),
                ('amount', models.IntegerField(default=0, verbose_name='сумма, ₽')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('succeeded', 'Успешно'), ('canceled', 'Отменён')], db_index=True, default='pending', max_length=16, verbose_name='статус')),
                ('confirmation_url', models.URLField(blank=True, max_length=500, verbose_name='ссылка на оплату')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ключ идемпотентности')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='ответ провайдера')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'платёж',
                'verbose_name_plural': 'платежи',
                'ordering': ['-created'],
            },
        ),
    ]
